In [1]:
import numpy as np

In [2]:
mylist = [1,2,3] 

In [3]:
type(mylist)

list

In [6]:
arr = np.array(mylist)

In [7]:
arr

array([1, 2, 3])

In [8]:
 mylist = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
mylist

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
mymatrix = np.array(mylist)

In [12]:
mymatrix.shape

(3, 3)

In [14]:
np.arange(0,10,2) # start inclusive and end exclusive.

array([0, 2, 4, 6, 8])

In [15]:
np.zeros(5) # creates a vector of float.

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.ones((5,5)) + 3  # broadcasting value to perform operations.

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [21]:
np.arange(0,10,2) + 1

array([1, 3, 5, 7, 9])

In [22]:
np.ones((5,5)) / 5

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [24]:
 #Linearly spaced arrays to return linearly spaced numbers:

np.linspace(0,12,5) #inclusive start,inclusve stop nd how many no u want

array([ 0.,  3.,  6.,  9., 12.])

In [26]:
 np.eye(5) #Identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
#Indexing and Selection:
# Indexing allows us to grab a single element from a one dim or two dim array
# whereas,
# Selection allows us to grab a chunk of elements from arrays.

In [29]:
arr = np.arange(20,51,2)

In [30]:
arr

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [37]:
arr[0:5]  # [inclusive:exclusive]

array([20, 22, 24, 26, 28])

In [32]:
arr[:5]

array([20, 22, 24, 26, 28])

In [33]:
arr[6:]

array([32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [34]:
arr[-1]

50

In [36]:
arr[:-1]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [38]:
arr[:5] - 5

array([15, 17, 19, 21, 23])

In [39]:
arr

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [40]:
arr[-1] **2

2500

 ### IMPORTANT OBSERVATION:

In [41]:
arr

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [51]:
sliced_arr = arr[0:5] # This assignment is still directly pointing to the original array

In [48]:
sliced_arr

array([20, 22, 24, 26, 28])

In [49]:
sliced_arr[:] = 99

In [50]:
arr

array([99, 99, 99, 99, 99, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [52]:
# Observe that the sliced_arr was sliced from the arr, but still directly pointing to the original array

In [53]:
# If you do not want that the original array to get affected, then use
# the method copy():

arr_copy = arr.copy()

In [54]:
arr_copy

array([99, 99, 99, 99, 99, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [55]:
arr_copy[:] = 100

In [56]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100])

In [57]:
arr

array([99, 99, 99, 99, 99, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50])

In [58]:
# Check that, after using copy function, the sliced array dint had any affect on original array, coz its no more pointing to original array.!

In [60]:
# Indexing on 2D Array i.e Matrix:

In [61]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [62]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
arr_2d.shape

(3, 3)

In [64]:
arr_2d[1]

array([4, 5, 6])

In [66]:
arr_2d[1][2]

6

In [71]:
arr_2d[1,2]

6

In [72]:
arr_2d[2,2]

9

In [78]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [80]:
# Array comparison returns boolean:

In [88]:
arr = np.arange(32,101,15)

In [89]:
arr

array([32, 47, 62, 77, 92])

In [90]:
arr>50

array([False, False,  True,  True,  True])

In [91]:
arr[arr>50] # Conditional selection of data, returns only those records
# where index are true

array([62, 77, 92])

In [92]:
arr[arr%2==0]

array([32, 62, 92])

In [94]:
arr

array([32, 47, 62, 77, 92])

In [95]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
arr_2d.mean(axis=1) # axis = 1, means across the columns!

array([2., 5., 8.])

In [102]:
arr_2d.mean(axis=0) # Giving mean across the rows! OR along the columns!

array([4., 5., 6.])

In [ ]:
# Assignment:

In [107]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [108]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [110]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [111]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [119]:
np.random.rand(1)

array([0.0827549])

In [120]:
np.random.randn(25)

array([-1.41036057,  0.37450017,  1.34144003, -0.26265802,  1.00484827,
        1.11762527, -0.83062375, -1.37054533,  1.24647903,  0.44864506,
       -0.22207723,  0.29832622,  0.58481439,  1.33161641,  0.38585596,
       -0.31204164,  0.56865902, -0.40164265, -0.45491607, -0.38784387,
       -1.35879832,  0.33953021,  0.12203838, -0.36257606,  0.89424885])

In [123]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [124]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [125]:
mat = np.arange(1,26).reshape(5,5)

In [126]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [127]:
mat [2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [128]:
mat[3,4]

20

In [130]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [131]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [132]:
mat[-2:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [133]:
np.std(mat)

7.211102550927978

In [135]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [136]:
# We worked a lot with random data in numpy, but is there a way to get the same random number evertime:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])